name: Build, test and deploy eshop workflow
on:
  push:
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{secrets.WORKFLOW_TOKEN}}
      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{hashFiles('**/package-lock.json')}}
          restore-keys: node_modules-
      - name: Install packages with npm
        run: |
          npm ci

  Build:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{secrets.WORKFLOW_TOKEN}}
      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{hashFiles('**/package-lock.json')}}
      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

      - name: Cache node modules and build folder
        if: ${{github.ref == 'refs/heads/master'}}
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{runner.os}}-build-${{github.run_id}}
          restore-keys: ${{runner.os}}-build-${{github.run_id}}

  Test:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{secrets.WORKFLOW_TOKEN}}
      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{hashFiles('**/package-lock.json')}}
      - name: Run test
        run: |
          npm run test -- --colors

  Deploy:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{secrets.WORKFLOW_TOKEN}}
      - name: Load Node modules and build folder
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{runner.os}}-build-${{github.run_id}}
      - name: Python dependencies install
        run: |
          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto
          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3
      - name: Setup ssh
        run:
          eval `ssh-agent -s`
      - name: Save key to file
        run: |
          mkdir ~/.ssh
          echo -e ${{secrets.AWS_KEY}} > ~/.ssh/key_sp.pem
          chmod 700 ~/.ssh/key_sp.pem
      - name: Deploy to EC2
        uses: aimerib/ansible-playwright@v2.7.7
        with:
          playbook: ec2_deploy.yml
          directory: ansible
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --user ec2-user
            --key-file ~/.ssh/key_sp.pem
